version: '3.4'

# variables from .env

services:
  nextcloud:
    volumes:
      - ${GRID_CERTIFICATES}:/etc/grid-security/certificates:ro
    #secrets:
    #  - myproxy_password
    ports:
      - 28080:80

#secrets:
#  myproxy_password:
#    file: ./myproxy_password
