version: '3.4'

services:
  nextcloud:
    hostname: nextcloud
    build:
      context: ./nextcloud
      args:
        - NEXTCLOUD_VERSION=21
        #- GFARM_SRC_URL=https://github.com/oss-tsukuba/gfarm/archive/refs/tags/2.7.19.tar.gz
        - GFARM_SRC_GIT_URL=https://github.com/oss-tsukuba/gfarm.git
        - GFARM_SRC_GIT_BRANCH=2.7
        #- GFARM2FS_SRC_URL=https://github.com/oss-tsukuba/gfarm2fs/archive/refs/tags/1.2.15.tar.gz
        - GFARM2FS_SRC_GIT_URL=https://github.com/oss-tsukuba/gfarm2fs.git
        - GFARM2FS_SRC_GIT_BRANCH=master
    volumes:
      - ./gfarm2rc:/gfarm2rc:ro
      - ./gfarm_shared_key:/gfarm_shared_key:ro
      - ./gfarm2.conf:/gfarm2.conf:ro
      - nextcloud:/var/www/html
      - log:/var/log
    depends_on:
      - mariadb
    security_opt:
      ### for fuse
      - apparmor:unconfined
    cap_add:
      ### for fuse
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    privileged: false
    secrets:
      - admin_password
      - db_password
      # - myproxy_password
      # - grid_proxy_password

  mariadb:
    hostname: mariadb
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    image: mariadb:10.5
    volumes:
      - db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    secrets:
      - db_password

secrets:
  admin_password:
    file: ./admin_password
  db_password:
    file: ./db_password
  # myproxy_password:
  #   file: ./myproxy_password
  # grid_proxy_password:
  #   file: ./grid_proxy_password

volumes:
  nextcloud:
  log:
  db:
