version: '3.4'

services:
  nextcloud:
    hostname: nextcloud
    build:
      context: ./nextcloud
      args:
        - http_proxy=${http_proxy:-}
        - https_proxy=${https_proxy:-}
        - NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION:-21}
        #- GFARM_SRC_URL=https://github.com/oss-tsukuba/gfarm/archive/refs/tags/2.7.19.tar.gz
        - GFARM_SRC_GIT_URL=https://github.com/oss-tsukuba/gfarm.git
        - GFARM_SRC_GIT_BRANCH=2.7
        #- GFARM2FS_SRC_URL=https://github.com/oss-tsukuba/gfarm2fs/archive/refs/tags/1.2.15.tar.gz
        - GFARM2FS_SRC_GIT_URL=https://github.com/oss-tsukuba/gfarm2fs.git
        - GFARM2FS_SRC_GIT_BRANCH=master
    environment:
      - NEXTCLOUD_GFARM_DEBUG=${NEXTCLOUD_GFARM_DEBUG:-0}
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      - GFARM_USER=${GFARM_USER}
      - GFARM_DATA_PATH=${GFARM_DATA_PATH}
      - GFARM_BACKUP_PATH=${GFARM_BACKUP_PATH}
      - NEXTCLOUD_BACKUP_TIME=${NEXTCLOUD_BACKUP_TIME}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - OVERWRITEHOST=${OVERWRITEHOST}
      - GRID_PROXY_HOURS=${GRID_PROXY_HOURS:-168}
      - MYPROXY_SERVER=${MYPROXY_SERVER:-}
      - MYPROXY_USER=${MYPROXY_USER}
      - GFARM_ATTR_CACHE_TIMEOUT=${GFARM_ATTR_CACHE_TIMEOUT:-180}
      - FUSE_ENTRY_TIMEOUT=${FUSE_ENTRY_TIMEOUT:-180}
      - FUSE_NEGATIVE_TIMEOUT=${FUSE_NEGATIVE_TIMEOUT:-5}
      - FUSE_ATTR_TIMEOUT=${FUSE_ATTR_TIMEOUT:-180}
    volumes:
      - ${GFARM2_CONF}:/gfarm2.conf:ro
      - ${GFARM2RC:-/dev/null}:/gfarm2rc:ro
      ### need to override when required
      #- ${GFARM_SHARED_KEY}:/gfarm_shared_key:ro
      #- ${GRID_CERTIFICATES}:/etc/grid-security/certificates:ro
      - nextcloud:/var/www/html
      - log:/var/log
    #depends_on:
    #  - mariadb
    security_opt:
      ### for fuse
      - apparmor:unconfined
    cap_add:
      ### for fuse
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    privileged: false
    secrets:
      - admin_password
      - db_password
      # - myproxy_password
      # - grid_proxy_password

  mariadb:
    hostname: mariadb
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    image: mariadb:10.5
    volumes:
      - db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    secrets:
      - db_password

secrets:
  admin_password:
    file: ./admin_password
  db_password:
    file: ./db_password
  # myproxy_password:
  #   file: ./myproxy_password
  # grid_proxy_password:
  #   file: ./grid_proxy_password

volumes:
  nextcloud:
  log:
  db:
