version: '3.4'

# variables from .env

services:
  nextcloud:
    environment:
      - VIRTUAL_HOST=${SERVER_NAME}

  proxy:
    build: ./proxy
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    environment:
      - DEFAULT_HOST=${SERVER_NAME}
      - HTTP_PORT=${HTTP_PORT}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html

volumes:
  html:
